apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: unified-graphics-webserver
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: unified-graphics.127.0.0.1.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: unified-graphics-webserver
                port:
                  number: 80
