apiVersion: apps/v1
kind: Deployment
metadata:
  name: unified-graphics-webserver
spec:
  template:
    spec:
      containers:
        - name: unified-graphics-webserver
          envFrom:
            - configMapRef:
                name: unified-graphics-webserver-config
          # FIXME - we should explore dissallowing privilege escalation
          securityContext:
            allowPrivilegeEscalation: true # Default behavior
            runAsNonRoot: false # Default behavior. VLab uses "true" in their environments
