[tool.poetry]
name = "unified-graphics"
version = "0.1.0"
description = ""
authors = [
    "Ian McGinnis <ian.mcginnis@noaa.gov>",
    "W. Evan Sheehan <evan.sheehan@noaa.gov>"
]

[tool.poetry.dependencies]
python = "~3.10"
Flask = "^3.0.0"
netCDF4 = "^1.6.3"
xarray = "^2023.9.0"
h5netcdf = "^1.1.0"
scipy = "^1.11.3"
# Use permissive versions to resolve dependency hell with boto3 & aiobotocore
aiobotocore = {version = "*", extras = ["boto3"]}
fsspec = "*"
s3fs = "*"
zarr = "^2.16.1"
flask-sqlalchemy = "^3.1.1"
psycopg = {version = "^3.1.12", extras = ["binary", "pool"]}
alembic = "^1.12.0"
pyarrow = "^13.0.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4"
mypy = "^1.5"
black = "^23.9.1"
flake8 = "^6.1.0"
coverage = "^7.3.1"
isort = "^5.10.1"
python-dotenv = "^1.0.0"
pandas-stubs = "^2.1.1.230928"
moto = {extras = ["server"], version = "^4.2.5"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"

[tool.poetry.scripts]
s3_bulk_rename = "utils.s3.s3_bulk_renaming:main"
