[tool.poetry]
name = "unified-graphics"
version = "0.1.0"
description = ""
authors = [
    "Ian McGinnis <ian.mcginnis@noaa.gov>",
    "W. Evan Sheehan <evan.sheehan@noaa.gov>"
]

[tool.poetry.dependencies]
python = "~3.9"
Flask = "^2.3.2"
netCDF4 = "^1.6.3"
xarray = "^2023.3.0"
h5netcdf = "^1.1.0"
scipy = "^1.10.0"
# Use permissive versions to resolve dependency hell with boto3 & aiobotocore
aiobotocore = {version = "*", extras = ["boto3"]}
fsspec = "*"
s3fs = "*"
zarr = "^2.14.1"
flask-sqlalchemy = "^3.0.3"
flask-alembic = "^2.0.1"
psycopg = "^3.1.9"

[tool.poetry.dev-dependencies]
pytest = "^7.3"
mypy = "^1.2"
black = "^23.3.0"
flake8 = "^6.0.0"
coverage = "^7.2.3"
isort = "^5.10.1"

[tool.poetry.group.dev.dependencies]
python-dotenv = "^1.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
