apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app.kubernets.io/name: ui
        # app.kubernets.io/instance:
        app.kubernets.io/part-of: unified-graphics
        app.kubernets.io/component: frontend
        app: graphics-ui
        tier: frontend
    name: graphics-ui
spec:
    replicas: 1
    selector:
        matchLabels:
            app: graphics-ui
    template:
        metadata:
            labels:
                app: graphics-ui
        spec:
            containers:
                - image: unified-graphics/ui
                  imagePullPolicy: Always
                  name: graphics-ui
                  # FIXME - we should specify resource limits to make sure pods don't dominate the nodes they're on
                  resources: {}
                  ports:
                      - containerPort: 80
                        protocol: TCP
                  # FIXME - we should explore dissallowing privilege escalation
                  securityContext:
                      allowPrivilegeEscalation: true # Default behavior
