"""Create Analysis and WeatherModel tables

Revision ID: 182066b45c15
Revises:
Create Date: 2023-05-12 09:34:45.580803

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "182066b45c15"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "weather_model",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=24), nullable=False),
        sa.Column("background_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["background_id"],
            ["weather_model.id"],
            name=op.f("fk_weather_model_background_id_weather_model"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_weather_model")),
        sa.UniqueConstraint(
            "name", "background_id", name=op.f("uq_weather_model_name")
        ),
    )
    op.create_table(
        "analysis",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("time", sa.DateTime(), nullable=False),
        sa.Column("domain", sa.String(length=24), nullable=False),
        sa.Column("frequency", sa.String(length=24), nullable=False),
        sa.Column("system", sa.String(length=24), nullable=False),
        sa.Column("model_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["weather_model.id"],
            name=op.f("fk_analysis_model_id_weather_model"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analysis")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("analysis")
    op.drop_table("weather_model")
    # ### end Alembic commands ###
