"""Create analysis tables

Revision ID: b0b0113fa957
Revises:
Create Date: 2023-05-04 07:04:24.347729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b0b0113fa957"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "weather_model",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=24), nullable=False),
        sa.Column("background_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["background_id"],
            ["weather_model.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "background_id"),
    )
    op.create_table(
        "analysis",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("time", sa.DateTime(), nullable=False),
        sa.Column("domain", sa.String(length=24), nullable=False),
        sa.Column("frequency", sa.String(length=24), nullable=False),
        sa.Column("system", sa.String(length=24), nullable=False),
        sa.Column("model_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["weather_model.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("analysis")
    op.drop_table("weather_model")
    # ### end Alembic commands ###
