apiVersion: apps/v1
kind: Deployment
metadata:
  name: unified-graphics-api
spec:
  template:
    spec:
      containers:
        - name: unified-graphics-api
          envFrom:
            - secretRef:
                name: unified-graphics-api-secret
            - configMapRef:
                name: unified-graphics-api-config
          # FIXME - we should explore dissallowing privilege escalation
          securityContext:
            allowPrivilegeEscalation: true # Default behavior
            runAsNonRoot: false # Default behavior. VLab uses "true" in their environments
      # Init containers to wait for our migrations
      initContainers:
      - name: wait-for-migration-job
        image: ghcr.io/groundnuty/k8s-wait-for:v1.7 # Use v2 for k8s >= v1.23
        imagePullPolicy: Always
        args:
        - "job"
        - "migrations"
