bases:
  - ../../../base/api
images:
  - name: unified-graphics/api
    newName: ghcr.io/noaa-gsl/unified-graphics/api
    newTag: main
patchesStrategicMerge:
  - patch_add_volume.yaml

configMapGenerator:
  - name: unified-graphics-api
    behavior: merge
    envs:
      - dev.api.env
