bases:
- ../../../base/api
namePrefix: dev-
images:
- name: unified-graphics/api
  newName: ghcr.io/noaa-gsl/unified-graphics/api
  newTag: main
commonLabels:
  environment: dev
namespace: dev
resources:
  - "namespace.yaml"
patchesStrategicMerge:
- patch_add_volume.yaml

configMapGenerator:
  - name: graphics-api
    behavior: merge
    envs:
      - dev.api.env
