bases:
  - ../../../base/api
images:
  - name: unified-graphics/api
    newName: ghcr.io/noaa-gsl/unified-graphics/api
    newTag: main

patchesStrategicMerge:
  - "deployment.yaml"

configMapGenerator:
  - name: unified-graphics-api-config
    envs:
      - dev.api.env

secretGenerator:
  - name: unified-graphics-api-secret
    envs:
    - .env # Should contain AWS_ACCESS_KEY, AWS_SECRET_ACCESS_KEY, AWS_SECRET_TOKEN
