bases:
- ../../../base/api
namePrefix: dev-
images:
- name: unified-graphics/api
  newName: ghcr.io/noaa-gsl/unified-graphics/api
  newTag: main
commonLabels:
  environment: dev
namespace: dev
resources:
  - "namespace.yaml"