apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: db
    app.kubernetes.io/part-of: unified-graphics
    app.kubernetes.io/component: database
    app: postgres
    tier: database
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - image: postgres:15
          imagePullPolicy: IfNotPresent
          name: postgres
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-secret
          volumeMounts:
            - name: postgres-persistent-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-persistent-storage
          persistentVolumeClaim:
            claimName: postgres-pv-claim
