apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432 # Port to forward to in the pod
      protocol: TCP
      name: http
  selector:
    app: postgres
  type: ClusterIP
