apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app.kubernetes.io/name: api
        # app.kubernetes.io/instance:
        app.kubernetes.io/part-of: unified-graphics
        app.kubernetes.io/component: backend
        app: unified-graphics-api
        tier: backend
    name: unified-graphics-api
spec:
    replicas: 1
    selector:
        matchLabels:
            app: unified-graphics-api
    template:
        metadata:
            labels:
                app: unified-graphics-api
        spec:
            containers:
                - image: unified-graphics/api
                  imagePullPolicy: Always # Since we're tracking a long-lived tag, we'll want to always check for updated images
                  name: unified-graphics-api
                  resources:
                      requests:
                          memory: "1Gi"
                          cpu: "0.5"
                      limits:
                          memory: "2Gi"
                          cpu: "1"
                  ports:
                      - containerPort: 80
                        protocol: TCP
                  # FIXME - we should explore dissallowing privilege escalation
                  securityContext:
                      allowPrivilegeEscalation: true # Default behavior
                  envFrom:
                      - configMapRef:
                            name: unified-graphics-api
