apiVersion: v1
kind: Service
metadata:
  labels:
    app: graphics-api
  name: graphics-api
spec:
  ports:
  - port: 4001
    targetPort: 80 # Port to forward to in the pod
    protocol: TCP
  selector:
    app: graphics-api
  type: NodePort
