bases:
  - ../../../base/ui
images:
  - name: unified-graphics/ui
    newName: ghcr.io/noaa-gsl/unified-graphics/ui
    newTag: main

patchesStrategicMerge:
  - "deployment.yaml"

configMapGenerator:
  - name: unified-graphics-ui-config
    envs:
      - dev.ui.env
