name: Cleanup Application PR images

on:
  pull_request:
    types: [closed]
    paths:
      - "src/**/*.py"
      - "src/**/*.html"
      - ".github/workflows/**"
      - ".github/scripts/**"
jobs:
  purge-ghcr-images:
    name: Cleanup PR images from ghcr.io
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup images
        uses: bots-house/ghcr-delete-image-action@v1.1.0
        with:
          owner: noaa-gsl
          name: unified-graphics/api
          token: ${{ secrets.GHCR_CLEANUP_PAT }}
          tag: ${{ github.head_ref }}
      - name: Cleanup images
        uses: bots-house/ghcr-delete-image-action@v1.1.0
        with:
          owner: noaa-gsl
          name: unified-graphics/data
          token: ${{ secrets.GHCR_CLEANUP_PAT }}
          tag: ${{ github.head_ref }}
  purge-ecr-images:
    name: Cleanup PR images from ECR
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }} # Dependabot changes aren't sent to VLab
    environment: vlab
    concurrency: vlab
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Cleanup image
        run: |
          aws ecr batch-delete-image \
            --repository-name rtma-vis/api \
            --image-ids imageTag=${{ github.head_ref }}
      - name: Cleanup image
        run: |
          aws ecr batch-delete-image \
            --repository-name rtma-vis/data \
            --image-ids imageTag=${{ github.head_ref }}
