name: Cleanup UI PR images

on:
  pull_request:
    types: [closed]
    paths:
      - '.nvmrc'
      - 'services/ui/**'
jobs:
  purge-ghcr-images:
    name: Cleanup PR images from ghcr.io
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup images
        uses: bots-house/ghcr-delete-image-action@v1.0.1
        with:
          owner: noaa-gsl
          name: unified-graphics/ui
          token: ${{ secrets.GHCR_CLEANUP_PAT }}
          tag: ${GITHUB_HEAD_REF}
  purge-ecr-images:
    name: Cleanup PR images from ECR
    runs-on: ubuntu-latest
    environment: vlab
    concurrency: vlab
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Cleanup image
        run: |
          aws ecr batch-delete-image \
            --repository-name rtma-viz/ui \
            --image-ids imageTag=${GITHUB_HEAD_REF}
